### ISSUE TITLE
How to use the FN key? 

### ISSUE THREAD

**Issue by damonms21** [Steppschuh/RemoteControlServer#125]
How do I use the Fn second function keyboard key?

**Comment by Steppschuh** [comment]
Hey,
there's no FN key available because there's no key event that the server could trigger for it. Usually these are integrated in the keyboard driver and send the key event that you want to access by using the FN key (like media or F1-F12 keys).

You can send these keys directly from the app though, without using the FN key in the first place. If you feel like there's something that you want to send that isn't available yet, let me know.
